import type { Command } from "../../api/command/Command";
import type { LogLevel } from "../../api/logging/LogLevel";
import type { Binding } from "../../api/binding/Binding";
import type { InteractionData } from "../../api/interaction/InteractionData";
import { UpdateBinder } from "./UpdateBinder";
import type { KeyInteractionCmdUpdateBinder } from "../../api/binder/KeyInteractionCmdUpdateBinder";
import type { Interaction } from "../../api/interaction/Interaction";
import type { Widget } from "../../api/binder/BaseBinderBuilder";
import type { BindingsObserver } from "../../api/binding/BindingsObserver";
import type { UndoHistory } from "../../api/undo/UndoHistory";
import type { Logger } from "../../api/logging/Logger";
export declare class KeysBinder<C extends Command, I extends Interaction<D>, D extends InteractionData> extends UpdateBinder<C, I, D> implements KeyInteractionCmdUpdateBinder<C, I, D> {
    private codes;
    private readonly checkCodeFn;
    constructor(undoHistory: UndoHistory, logger: Logger, observer?: BindingsObserver, binder?: Partial<KeysBinder<C, I, D>>);
    with(...keyCodes: ReadonlyArray<string>): KeysBinder<C, I, D>;
    on(widget: ReadonlyArray<Widget<EventTarget>> | Widget<EventTarget>, ...widgets: ReadonlyArray<Widget<EventTarget>>): KeysBinder<C, I, D>;
    onDynamic(node: Widget<Node>): KeysBinder<C, I, D>;
    first(fn: (c: C, i: D) => void): KeysBinder<C, I, D>;
    when(fn: (() => boolean) | ((i: D) => boolean)): KeysBinder<C, I, D>;
    ifHadEffects(fn: (c: C, i: D) => void): KeysBinder<C, I, D>;
    ifHadNoEffect(fn: (c: C, i: D) => void): KeysBinder<C, I, D>;
    ifCannotExecute(fn: (c: C, i: D) => void): KeysBinder<C, I, D>;
    end(fn: (c: C, i: D) => void): KeysBinder<C, I, D>;
    log(...level: ReadonlyArray<LogLevel>): KeysBinder<C, I, D>;
    stopImmediatePropagation(): KeysBinder<C, I, D>;
    preventDefault(): KeysBinder<C, I, D>;
    then(fn: ((c: C, i: D) => void) | ((c: C) => void)): KeysBinder<C, I, D>;
    continuousExecution(): KeysBinder<C, I, D>;
    strictStart(): KeysBinder<C, I, D>;
    throttle(timeout: number): KeysBinder<C, I, D>;
    cancel(fn: (i: D) => void): KeysBinder<C, I, D>;
    endOrCancel(fn: (i: D) => void): KeysBinder<C, I, D>;
    catch(fn: (ex: unknown) => void): KeysBinder<C, I, D>;
    name(name: string): KeysBinder<C, I, D>;
    toProduce<C2 extends Command>(fn: (i: D) => C2): KeysBinder<C2, I, D>;
    usingInteraction<I2 extends Interaction<D2>, D2 extends InteractionData>(fn: () => I2): KeysBinder<C, I2, D2>;
    protected duplicate(): KeysBinder<C, I, D>;
    bind(): Binding<C, I, D>;
}
