import type { Observable } from "rxjs";
import { Subject } from "rxjs";
import type { Command } from "../../api/command/Command";
import type { InteractionData } from "../../api/interaction/InteractionData";
import type { Binding } from "../../api/binding/Binding";
import type { Interaction } from "../../api/interaction/Interaction";
import type { UndoHistory } from "../../api/undo/UndoHistory";
import type { FSMHandler } from "../../api/fsm/FSMHandler";
import type { Logger } from "../../api/logging/Logger";
export declare class BindingImpl<C extends Command, I extends Interaction<D>, D extends InteractionData> implements Binding<C, I, D>, FSMHandler {
    protected _name: string | undefined;
    protected _timeEnded: number;
    protected _timeCancelled: number;
    protected _activated: boolean;
    protected readonly _interaction: I;
    protected _cmd?: C;
    readonly continuousCmdExecution: boolean;
    readonly strictStart: boolean;
    protected readonly cmdProducer: (i?: D) => C;
    protected readonly cmdsProduced: Subject<C>;
    protected undoHistory: UndoHistory;
    protected logger: Logger;
    logBinding: boolean;
    logCmd: boolean;
    logUsage: boolean;
    constructor(continuousExecution: boolean, strict: boolean, interaction: I, cmdProducer: (i?: D) => C, widgets: ReadonlyArray<EventTarget>, undoHistory: UndoHistory, logger: Logger, name?: string);
    get name(): string;
    when(): boolean;
    clearEvents(): void;
    protected createCommand(): C | undefined;
    catch(_err: undefined): void;
    first(): void;
    then(): void;
    end(): void;
    cancel(): void;
    endOrCancel(): void;
    ifCmdHadNoEffect(): void;
    ifCmdHadEffects(): void;
    ifCannotExecuteCmd(): void;
    get interaction(): I;
    get command(): C | undefined;
    get activated(): boolean;
    set activated(activated: boolean);
    get running(): boolean;
    fsmCancels(): void;
    private cancelContinousWithEffectsCmd;
    fsmStarts(): void;
    fsmUpdates(): void;
    private continuousExecutionOnFSMUpdate;
    fsmStops(): void;
    private executeCommandOnFSMStop;
    private createAndInitCommand;
    private afterCmdExecuted;
    uninstallBinding(): void;
    get produces(): Observable<C>;
    get timesEnded(): number;
    get timesCancelled(): number;
}
